### ISSUE TITLE
Clean routines for writing full HDF VSANS files

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#450]
full data sets, including simulated data, attributes, and the native data types.

 Necessary to re-save data if it needs to be altered/repaired, and also for generating viable fake data sets to test the reduction process with "true" detector data that needs all of the corrections

**Comment by srkline-igor** [comment]
this works as well as it needs to - the easiest way to write out a VSANS file is to duplicate an existing file, since NICE can (and has for a long time) write out proper files. Then I can simply modify these already correct files with whatever I need to add or update. Much easier and more reliable than me trying to do it all myself.
