### ISSUE TITLE
Move away from using local copy of data files?

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#552]
Some operations (Transmission, patch, etc. ) read from the local copies if possible, for a significant speed boost.

This creates a problem of the "cached" data being out of date, and not knowing when to refresh.

So do I drop this all together and speed up the file read? Periodically force a refresh of the catalog?

**Comment by srkline-igor** [comment]
Leave the file read from local copies - there is no way to speed up the file read of a file that is 4 MB in size more than it is right now. Any procedure that changes the metadata (like patch) must take the extra step of killing the data files that it touched so that the file will be read in from disk on the next access.
