### ISSUE TITLE
PATCH speedup

### ISSUE THREAD

**Issue by krzywon** [sansigormacros/ncnrsansigormacros#596]
Add a flag for patch so that it does not wipe out all of the RawVSANS data if nothing had been changed. 

Can I flag only the files that have been changed, and immediately remove those to then reload just the changed files?

**Comment by srkline-igor** [comment]
Safer to wipe out all of the data and force a fresh reload of all of the data files, just in case there is stale data from some other operation lying around. Patching is not used frequently (as far as I know) so the speed hit is minimal, especially since once the metadata has been corrected, it's done. Trying to keep a running list of files that have been "touched" is possible, but prone to errors.
